######### Basic Settings #########
basic:
    device: '4'
    seed: [1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: cifar10
    shuffle: true

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: cnn_prompt_joint
    incre_type: cil
    # eval_metric Choises: acc, recall
    eval_metric: acc

    apply_nme: true

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18_cbam
    pretrained: true
    freeze: true
    save_models: false # if true, programm will save model's weights during incremental train

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    init_cls: 10
    increment: 10


######### Method's Hyperparameters #########
special:
    gamma: 1
    prompt_size: 32    

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    cifar100: 
        resnet18_cbam:
            pretrain_path: pretrain_weights/imagenet200_resnet18_cbam_pretrained.pth
            opt_type: adam
            epochs: 200 #80
            lrate: 0.001
            scheduler: multi_step
            milestones: [60,120,160]
            lrate_decay: 0.1
            batch_size: 128
            num_workers: 8
    
    cifar10: 
        resnet18_cbam:
            pretrain_path: pretrain_weights/imagenet200_resnet18_cbam_pretrained.pth
            opt_type: adam
            epochs: 200 #80
            lrate: 0.001
            scheduler: multi_step
            milestones: [60,120,160]
            lrate_decay: 0.1
            batch_size: 128
            num_workers: 8
            
