######### Basic Settings #########
basic:
    device: '4'
    seed: [1993] # icarl 官方代码给的种子是 1993
    num_workers: 8

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: cifar100
    shuffle: true

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: finetune
    incre_type: til
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet32
    pretrained: false
    save_models: false # if true, programm will save model's weights during incremental train

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    init_cls: 10
    increment: 10


######### Method's Hyperparameters #########
# special:
    

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    cifar100: 
        resnet32:
            opt_type: adam  
            init_epochs: 200 #200
            init_lrate: 0.1
            init_scheduler: multi_step
            init_milestones: [60,120,160]
            init_lrate_decay: 0.1
            init_weight_decay: 0.0005

            epochs: 80 #80
            lrate: 0.1
            scheduler: multi_step
            milestones: [40, 70]
            lrate_decay: 0.1
            batch_size: 128
            weight_decay: 0.0002
            num_workers: 8
            
